[cite_start]name: CI/CD CRUD Kesehatan [cite: 43]
on:
  push:
    branches:
      - [cite_start]main [cite: 44, 45, 47]
jobs:
  deploy:
    [cite_start]runs-on: ubuntu-latest [cite: 48, 50]
    steps:
      - name: Checkout Code
        [cite_start]uses: actions/checkout@v2 [cite: 52, 53]
      - name: Setup SSH
        [cite_start]uses: webfactory/ssh-agent@v0.5.3 [cite: 54, 55]
        with:
          [cite_start]ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} [cite: 57]
      - name: Deploy ke EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@IP_EC2 << 'EOF' [cite: 60]
          cd /var/www/nama-project [cite: 61]
          git pull origin main [cite: 62]
          sudo systemctl restart nginx [cite: 63]
          EOF
